--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 17.4

-- Started on 2026-07-02 14:16:05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE beerme3;
--
-- TOC entry 4907 (class 1262 OID 24376)
-- Name: beerme3; Type: DATABASE; Schema: -; Owner: bob
--

CREATE DATABASE beerme3 WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE beerme3 OWNER TO bob;

\connect beerme3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4908 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 223 (class 1259 OID 40866)
-- Name: db_person; Type: TABLE; Schema: public; Owner: bob
--

CREATE TABLE public.db_person (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(50) NOT NULL,
    age integer NOT NULL,
    birth_date timestamp with time zone NOT NULL,
    id bigint NOT NULL
);


ALTER TABLE public.db_person OWNER TO bob;

--
-- TOC entry 222 (class 1259 OID 40865)
-- Name: db_person_id_seq; Type: SEQUENCE; Schema: public; Owner: bob
--

ALTER TABLE public.db_person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.db_person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 40872)
-- Name: db_track; Type: TABLE; Schema: public; Owner: bob
--

CREATE TABLE public.db_track (
    created_at timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    name character varying(50) NOT NULL,
    length numeric(5,2) NOT NULL,
    configuration character varying(50) NOT NULL,
    id bigint NOT NULL,
    city character varying(50),
    state character varying(50),
    short_name character varying(50) NOT NULL
);


ALTER TABLE public.db_track OWNER TO bob;

--
-- TOC entry 224 (class 1259 OID 40871)
-- Name: db_track_id_seq; Type: SEQUENCE; Schema: public; Owner: bob
--

ALTER TABLE public.db_track ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.db_track_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 40828)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: bob
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO bob;

--
-- TOC entry 220 (class 1259 OID 40827)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: bob
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 40902)
-- Name: logs; Type: TABLE; Schema: public; Owner: bob
--

CREATE TABLE public.logs (
    bpm integer DEFAULT 0 NOT NULL,
    reading_date date NOT NULL,
    dia integer DEFAULT 0 NOT NULL,
    ihb integer DEFAULT 0,
    mov integer DEFAULT 0,
    msg character varying DEFAULT '0'::character varying,
    sys integer DEFAULT 0,
    reading_time time without time zone NOT NULL,
    comments character varying,
    activity character varying,
    breakfast character varying,
    lunch character varying,
    dinner character varying,
    snacks character varying
);


ALTER TABLE public.logs OWNER TO bob;

--
-- TOC entry 216 (class 1259 OID 24399)
-- Name: nascar_results; Type: TABLE; Schema: public; Owner: bob
--

CREATE TABLE public.nascar_results (
    race_date date NOT NULL,
    track character varying NOT NULL,
    driver character varying NOT NULL,
    pos integer DEFAULT 0 NOT NULL,
    greg_pick boolean DEFAULT false NOT NULL,
    bob_pick boolean NOT NULL,
    track_id integer
);


ALTER TABLE public.nascar_results OWNER TO bob;

--
-- TOC entry 4909 (class 0 OID 0)
-- Dependencies: 216
-- Name: COLUMN nascar_results.pos; Type: COMMENT; Schema: public; Owner: bob
--

COMMENT ON COLUMN public.nascar_results.pos IS 'drivers finish position';


--
-- TOC entry 228 (class 1259 OID 40964)
-- Name: races; Type: TABLE; Schema: public; Owner: bob
--

CREATE TABLE public.races (
    race_id integer NOT NULL,
    race_date date NOT NULL,
    race_name character varying NOT NULL,
    track_id integer NOT NULL,
    television character varying,
    race_winner character varying
);


ALTER TABLE public.races OWNER TO bob;

--
-- TOC entry 217 (class 1259 OID 24408)
-- Name: seq_nascar_results; Type: SEQUENCE; Schema: public; Owner: bob
--

CREATE SEQUENCE public.seq_nascar_results
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.seq_nascar_results OWNER TO bob;

--
-- TOC entry 219 (class 1259 OID 40826)
-- Name: seq_track_id; Type: SEQUENCE; Schema: public; Owner: bob
--

CREATE SEQUENCE public.seq_track_id
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.seq_track_id OWNER TO bob;

--
-- TOC entry 218 (class 1259 OID 40811)
-- Name: tracks; Type: TABLE; Schema: public; Owner: bob
--

CREATE TABLE public.tracks (
    track_name character varying NOT NULL,
    id integer NOT NULL
);


ALTER TABLE public.tracks OWNER TO bob;

--
-- TOC entry 4897 (class 0 OID 40866)
-- Dependencies: 223
-- Data for Name: db_person; Type: TABLE DATA; Schema: public; Owner: bob
--

COPY public.db_person (created_at, updated_at, name, age, birth_date, id) FROM stdin;
2026-05-05 17:40:13.399366-04	2026-05-05 17:40:13.428719-04	John Toe	30	1963-02-05 01:00:00-05	1
\.


--
-- TOC entry 4899 (class 0 OID 40872)
-- Dependencies: 225
-- Data for Name: db_track; Type: TABLE DATA; Schema: public; Owner: bob
--

COPY public.db_track (created_at, "updatedAt", name, length, configuration, id, city, state, short_name) FROM stdin;
2026-05-06 19:14:48.209303-04	2026-05-06 19:14:48.209323-04	Bristol Motor Speedway	0.53	concrete oval	92	Bristol	Tennessee	Bristol
2026-05-06 19:14:48.210792-04	2026-05-06 19:14:48.2108-04	Charlotte Motor Speedway	1.50	paved quad oval	93	Charlotte	North Carolina	Charlotte
2026-05-06 19:14:48.211224-04	2026-05-06 19:14:48.21123-04	Circuit of the Americas	2.33	paved road course	94	Austin	Texas	COTA
2026-05-06 19:14:48.211561-04	2026-05-06 19:14:48.211566-04	Darlington Raceway	1.34	paved egg shaped oval	95	Darlington	South Carolina	Darlington
2026-05-06 19:14:48.211868-04	2026-05-06 19:14:48.211872-04	Daytona International Speedway	2.50	paved tri oval	96	Daytona	Florida	Daytona
2026-05-06 19:14:48.212157-04	2026-05-06 19:14:48.212161-04	Dover Motor Speedway	1.00	concrete oval	97	Dover	Delaware	Dover
2026-05-06 19:14:48.21246-04	2026-05-06 19:14:48.212464-04	EchoPark Speedway	1.54	paved quad oval	98	Atlanta	Georgia	Atlanta
2026-05-06 19:14:48.212797-04	2026-05-06 19:14:48.212804-04	Homestead–Miami Speedway	1.50	paved oval	99	Miami	Florida	Miami
2026-05-06 19:14:48.213141-04	2026-05-06 19:14:48.213146-04	Indianapolis Motor Speedway	2.50	paved rectangular oval	100	Speedway	Indiana	Indianapolis
2026-05-06 19:14:48.21344-04	2026-05-06 19:14:48.213445-04	Iowa Speedway	0.88	paved d-shaped oval	101	Newton	Iowa	Iowa
2026-05-06 19:14:48.213727-04	2026-05-06 19:14:48.213731-04	Kansas Speedway	1.50	paved tri oval	102	Kansas City	Kansas	Kansas
2026-05-06 19:14:48.213996-04	2026-05-06 19:14:48.214-04	Las Vegas Motor Speedway	1.50	paved tri oval	103	Las Vegas	Nevada	Las Vegas
2026-05-06 19:14:48.214255-04	2026-05-06 19:14:48.214258-04	Martinsville Speedway	0.53	paved concrete paperclip-shaped oval	104	Ridgeway	Virginia	Martinsville
2026-05-06 19:14:48.214513-04	2026-05-06 19:14:48.214517-04	Michigan International Speedway	2.00	paved d-shaped oval	105	Brooklyn	Michigan	Michigan
2026-05-06 19:14:48.214774-04	2026-05-06 19:14:48.214778-04	Nashville International Speedway	1.33	concrete tri oval	106	Nashville	Tennessee	Nashville
2026-05-06 19:14:48.21503-04	2026-05-06 19:14:48.215033-04	New Hampshire Motor Speedway	1.06	paved paper-clip-shaped oval	107	Loudon	New Hampshire	New Hampshire
2026-05-06 19:14:48.215282-04	2026-05-06 19:14:48.215286-04	North Wilkesboro Speedway	0.63	paved oval	108	North Wilkesboro	North Carolina	North Wilkesboro
2026-05-06 19:14:48.215538-04	2026-05-06 19:14:48.215542-04	Phoenix Raceway	1.50	paved dogleg oval	109	Avondale	Arizona	Phoenix
2026-05-06 19:14:48.215964-04	2026-05-06 19:14:48.215977-04	Pocono Speedway	2.50	paved triangular oval	110	Long Pond	Pennsylvania	Pocono
2026-05-06 19:14:48.216405-04	2026-05-06 19:14:48.21641-04	Richmond Raceway	0.75	paved d-shaped oval	111	Richmond	Virginia	Richmond
2026-05-06 19:14:48.216757-04	2026-05-06 19:14:48.216763-04	Talladega Superspeedway	2.66	paved tri oval	112	Lincoln	Alabama	Talladega
2026-05-06 19:14:48.217083-04	2026-05-06 19:14:48.217087-04	Watkins Glen International	2.45	paved road course	113	Watkins Glen	New York	Watkins Glen
2026-05-06 19:14:48.217377-04	2026-05-06 19:14:48.217381-04	World Wide Technology Raceway	1.25	paved egg shaped oval	114	Madison	Illinois	World Wide Technology Raceway
\.


--
-- TOC entry 4895 (class 0 OID 40828)
-- Dependencies: 221
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: bob
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
7	db	0001_initial	2026-05-05 18:20:21.310887-04
8	db	0002_track_unique_name	2026-05-05 18:36:41.821949-04
9	db	0003_alter_track_length	2026-05-06 11:21:22.756933-04
10	db	0004_track_city_track_state	2026-05-06 11:29:00.20669-04
11	db	0005_track_short_name	2026-05-06 13:24:17.467348-04
\.


--
-- TOC entry 4900 (class 0 OID 40902)
-- Dependencies: 227
-- Data for Name: logs; Type: TABLE DATA; Schema: public; Owner: bob
--

COPY public.logs (bpm, reading_date, dia, ihb, mov, msg, sys, reading_time, comments, activity, breakfast, lunch, dinner, snacks) FROM stdin;
\.


--
-- TOC entry 4890 (class 0 OID 24399)
-- Dependencies: 216
-- Data for Name: nascar_results; Type: TABLE DATA; Schema: public; Owner: bob
--

COPY public.nascar_results (race_date, track, driver, pos, greg_pick, bob_pick, track_id) FROM stdin;
\.


--
-- TOC entry 4901 (class 0 OID 40964)
-- Dependencies: 228
-- Data for Name: races; Type: TABLE DATA; Schema: public; Owner: bob
--

COPY public.races (race_id, race_date, race_name, track_id, television, race_winner) FROM stdin;
\.


--
-- TOC entry 4892 (class 0 OID 40811)
-- Dependencies: 218
-- Data for Name: tracks; Type: TABLE DATA; Schema: public; Owner: bob
--

COPY public.tracks (track_name, id) FROM stdin;
Bowman Gray Stadium	87
Daytona International Spe…	88
Atlanta Motor Speedway	89
Circuit of The Americas	90
Phoenix Raceway	91
Las Vegas Motor Speedway	92
Darlington Raceway	93
Martinsville Speedway	94
Bristol Motor Speedway	95
Kansas Speedway	96
Talladega Superspeedway	97
Texas Motor Speedway	98
Watkins Glen Internationa…	99
Dover Motor Speedway	100
Charlotte Motor Speedway	101
Nashville Superspeedway	102
Michigan International Sp…	103
Pocono Raceway	104
Coronado Street Course	105
Sonoma Raceway	106
Chicagoland Speedway	107
North Wilkesboro Speedway	108
Indianapolis Motor Speedw…	109
Iowa Speedway	110
Richmond Raceway	111
New Hampshire Motor Speed…	112
World Wide Technology Rac…	113
Homestead Miami Speedway	114
\.


--
-- TOC entry 4910 (class 0 OID 0)
-- Dependencies: 222
-- Name: db_person_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bob
--

SELECT pg_catalog.setval('public.db_person_id_seq', 1, true);


--
-- TOC entry 4911 (class 0 OID 0)
-- Dependencies: 224
-- Name: db_track_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bob
--

SELECT pg_catalog.setval('public.db_track_id_seq', 347, true);


--
-- TOC entry 4912 (class 0 OID 0)
-- Dependencies: 220
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bob
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 11, true);


--
-- TOC entry 4913 (class 0 OID 0)
-- Dependencies: 217
-- Name: seq_nascar_results; Type: SEQUENCE SET; Schema: public; Owner: bob
--

SELECT pg_catalog.setval('public.seq_nascar_results', 44, true);


--
-- TOC entry 4914 (class 0 OID 0)
-- Dependencies: 219
-- Name: seq_track_id; Type: SEQUENCE SET; Schema: public; Owner: bob
--

SELECT pg_catalog.setval('public.seq_track_id', 114, true);


--
-- TOC entry 4736 (class 2606 OID 40870)
-- Name: db_person db_person_pkey; Type: CONSTRAINT; Schema: public; Owner: bob
--

ALTER TABLE ONLY public.db_person
    ADD CONSTRAINT db_person_pkey PRIMARY KEY (id);


--
-- TOC entry 4738 (class 2606 OID 40876)
-- Name: db_track db_track_pkey; Type: CONSTRAINT; Schema: public; Owner: bob
--

ALTER TABLE ONLY public.db_track
    ADD CONSTRAINT db_track_pkey PRIMARY KEY (id);


--
-- TOC entry 4734 (class 2606 OID 40834)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: bob
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4742 (class 2606 OID 40914)
-- Name: logs newtable_unique; Type: CONSTRAINT; Schema: public; Owner: bob
--

ALTER TABLE ONLY public.logs
    ADD CONSTRAINT newtable_unique UNIQUE (reading_date, reading_time);


--
-- TOC entry 4744 (class 2606 OID 40970)
-- Name: races races_pk; Type: CONSTRAINT; Schema: public; Owner: bob
--

ALTER TABLE ONLY public.races
    ADD CONSTRAINT races_pk PRIMARY KEY (race_id);


--
-- TOC entry 4730 (class 2606 OID 40817)
-- Name: tracks track_pk; Type: CONSTRAINT; Schema: public; Owner: bob
--

ALTER TABLE ONLY public.tracks
    ADD CONSTRAINT track_pk PRIMARY KEY (id);


--
-- TOC entry 4732 (class 2606 OID 40819)
-- Name: tracks track_unique; Type: CONSTRAINT; Schema: public; Owner: bob
--

ALTER TABLE ONLY public.tracks
    ADD CONSTRAINT track_unique UNIQUE (track_name);


--
-- TOC entry 4740 (class 2606 OID 40878)
-- Name: db_track unique_name; Type: CONSTRAINT; Schema: public; Owner: bob
--

ALTER TABLE ONLY public.db_track
    ADD CONSTRAINT unique_name UNIQUE (name);


--
-- TOC entry 4728 (class 1259 OID 24410)
-- Name: nascar_results_race_date_idx; Type: INDEX; Schema: public; Owner: bob
--

CREATE UNIQUE INDEX nascar_results_race_date_idx ON public.nascar_results USING btree (race_date, track, driver);


--
-- TOC entry 4745 (class 2606 OID 40820)
-- Name: nascar_results nascar_results_track_fk; Type: FK CONSTRAINT; Schema: public; Owner: bob
--

ALTER TABLE ONLY public.nascar_results
    ADD CONSTRAINT nascar_results_track_fk FOREIGN KEY (track_id) REFERENCES public.tracks(id);


--
-- TOC entry 4746 (class 2606 OID 40971)
-- Name: races races_tracks_fk; Type: FK CONSTRAINT; Schema: public; Owner: bob
--

ALTER TABLE ONLY public.races
    ADD CONSTRAINT races_tracks_fk FOREIGN KEY (track_id) REFERENCES public.tracks(id);


-- Completed on 2026-07-02 14:16:06

--
-- PostgreSQL database dump complete
--

